language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.6
      env: COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_EXTRA_ARGS
  - travis_retry composer create-project --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint
  - travis_retry composer create-project --no-interaction kdyby/code-checker /tmp/code-checker

script:
  - vendor/bin/tester -p php ./tests/
  - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - php /tmp/code-checker/src/code-checker.php --short-arrays

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
